### PR TITLE
ril: Fix network operator search

### PR DESCRIPTION
**Pull request by eleboucher**

### CODE REVIEW

**Comment by eleboucher** [comment]
possible fix, untested atm (i'll if my cm13 source want to build )

**Comment by sktjdgns1189** [comment]
Don't request a pull if it's untested.
And please learn how to do a git commit with authorship untouched.

**Comment by eleboucher** [comment]
That come from g4 lol

**Comment by sktjdgns1189** [comment]
You're mistaken if you think G4's RIL is, in the least amount of bit, compatible with the S6.
And correct me if I'm wrong, but invisiblek holds the original authorship.

ps, this issue has opened since we've switched to opensource RIL implementation.

**Comment by eleboucher** [comment]
well see by yourself https://github.com/CyanogenMod/android_device_lge_g4-common/commit/168b73870ee1cef38ceb6afa8c1db0f404ef555d 
if you switched to opensource ril then this will help i'm building with it let's see
ps first try on a exynos devices (i don't own the device)

**Comment by arter97** [comment]
mQANElements is 6 on the S6 with current RIL.
Setting it to 5 doesn't fix this.

**Comment by eleboucher** [comment]
how sure you are ?

**Comment by arter97** [comment]
Because I've tested it?
Most likely it'll be related to hardware/samsung with new ss333 stuffs.

**Comment by eleboucher** [comment]
as soon as i will have the logs i'll investigate

**Comment by arter97** [comment]
Maybe you should get yourself an S6 first rofl ditch the G4 eh

**Comment by eleboucher** [comment]
well donate me one :p

**Comment by eleboucher** [comment]
btw don't forget that QAN means query available networks

**Pull request closed without merging**
